title: Reef Referral Documentation
description: Learn how to get started with our referral system for iOS subscription apps.
theme: just-the-docs
color_scheme: reef


url: https://docs.reefreferral.com/
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.png"


aux_links:
  Home: https://reefreferral.com

callouts:
  warning:
    title: â—ï¸Warning
    color: red
  note:
    title: ğŸ“˜ Note
    color: blue
  alert:
    title: ğŸš§ Alert
    color: yellow
  done:
    title: ğŸ‘ Done
    color: green

